name: AutoRun UnitTests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  linux_tests:
  
    runs_on: ubuntu-latest
    
    steps:
        - uses: actions/checkout@v3

        - name: unittests
          run: |
            echo python3 Lysenko_Egor_M3114\tests\circle.py
            echo python3 Lysenko_Egor_M3114\tests\rectangle.py
            echo python3 Lysenko_Egor_M3114\tests\square.py
            echo python3 Lysenko_Egor_M3114\tests\triangle.py

            
  Windows_tests:
  
    runs_on: windows-latest
    
    steps:
        - uses: actions/checkout@v3

        - name: unittests
          run: |
            echo python3 Lysenko_Egor_M3114\tests\circle.py
            echo python3 Lysenko_Egor_M3114\tests\rectangle.py
            echo python3 Lysenko_Egor_M3114\tests\square.py
            echo python3 Lysenko_Egor_M3114\tests\triangle.py
